name: Test HAR Upload
on:
  push:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test file
        run: echo "hello from github actions" > hello.txt

      - name: Upload to HAR
        uses: sameekshamalav/upload-to-har-action@v1
        with:
          harness_url:   https://pkg.qa.harness.io
          api_key:       ${{ secrets.HARNESS_API_KEY }}
          account_id:    ${{ secrets.HARNESS_ACCOUNT_ID }}
          registry:      ga_test
          artifact_name: hello-artifact
          version:       1.0.0
          file_path:     ./hello.txt