name: Test HAR Upload
on:
  push:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test file
        run: echo "hello from github actions" > hello.txt

      - name: Debug
        run: |
              echo "Key starts with: ${HARNESS_API_KEY:0:10}..."
              echo "Account ID: ${{ secrets.HARNESS_ACCOUNT_ID }}"
        env: 
          HARNESS_API_KEY: ${{ secrets.HARNESS_API_KEY }}
      - name: Raw curl from GitHub runner
        run: |
           echo "hello from github runner" > test.txt
           curl -X PUT "https://pkg.qa.harness.io/pkg/${{ secrets.HARNESS_ACCOUNT_ID }}/ga_test/files/hello-artifact/1.0.0/curl-test.txt" --header "x-api-key: ${{ secrets.HARNESS_API_KEY }}" \
           -T ./test.txt \
           -v 2>&1 | tail -30

      - name: Upload to HAR
        uses: sameekshamalav/upload-to-har-action@v1
        with:
          harness_url:   https://pkg.qa.harness.io
          api_key:       ${{ secrets.HARNESS_API_KEY }}
          account_id:    ${{ secrets.HARNESS_ACCOUNT_ID }}
          registry:      ga_test
          artifact_name: hello-artifact
          version:       1.0.0
          file_path:     ./hello.txt
